### ISSUE TITLE
the RGBA values not correct while hover to image

### ISSUE THREAD

**Issue by ankerSlicerTeam** [andyborrell/imgui_tex_inspect#9]
![image](https://github.com/andyborrell/imgui_tex_inspect/assets/135973681/0b77e3f9-4a31-4f18-bca2-9e43e1b5371c)

**Comment by ankerSlicerTeam** [comment]
it happens on Windows

**Comment by pthom** [comment]
Hum, this seems like a bug in [ImGuiTexInspect](https://github.com/andyborrell/imgui_tex_inspect)

The code for this demo is simple calling ImGuiTexInspect::ShowDemoWindow, see below:
```
int main(int, char **)
{
    HelloImGui::SetAssetsFolder(DemosAssetsFolder());
    HelloImGui::SimpleRunnerParams runnerParams{.guiFunction = ImGuiTexInspect::ShowDemoWindow, .windowSize={1000, 1000}};
    ImmApp::AddOnsParams addOnsParams;
    addOnsParams.withTexInspect = true;
    ImmApp::Run(runnerParams, addOnsParams);
    return 0;
}
```

If you need to inspect pixel values, I advise you to use ImmVision instead. See ImmVision tab in the [demo](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html)

**Comment by pthom** [comment]
Hello Andy, 

This issue is fixed in https://github.com/pthom/imgui_bundle/issues/211. It was due to using a reduced demo image size (to save space for the emscripten demos).
